#!/bin/sh 
exec kotlin -DmySysProp=somevalue -cp log4j-1.2.14.jar "$0" "$@"
!#
import org.apache.log4j.*

val logger = Logger.getLogger("mymodule").sure();

fun main(args: Array<String>) {
    BasicConfigurator.configure();
    logger.info("Hello from Kotlin via log4j! mySysProp=${System.getProperty("mySysProp")}")
}
